version: '3'
services:
  www:
    image: node:alpine
    working_dir: /var/www/html
    command: sh -c "apk add --no-cache apache2 && httpd -DFOREGROUND"
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443