version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=metunic
      - MYSQL_USER=metunic
      - MYSQL_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306